/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookshop;
import net.proteanit.sql.DbUtils;

//import com.sun.jdi.connect.spi.Connection;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Books extends javax.swing.JFrame {

    /**
     * Creates new form Books
     */
    public Books() {
        initComponents();
        DisplayBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BookIdTb = new javax.swing.JTextField();
        PriceTb = new javax.swing.JTextField();
        TitleTb = new javax.swing.JTextField();
        AuthorTb = new javax.swing.JTextField();
        QuantityTb = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        EditTb = new javax.swing.JButton();
        DeleteTb = new javax.swing.JButton();
        ResetTb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BooksTable = new javax.swing.JTable();
        PrintBtn = new javax.swing.JButton();
        labelField = new javax.swing.JLabel();
        CategoryTb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("ONLINE BOOK STORE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(371, 371, 371))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 60));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 70, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookshop/icon_small.PNG"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 70, 70));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setText("Books");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 70, 10));

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookshop/icon_small.PNG"))); // NOI18N
        User.setText("jLabel4");
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserMouseClicked(evt);
            }
        });
        jPanel2.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 70, 70));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Users");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("ID");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 116, 48, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Category");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 116, 99, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Title");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 116, 105, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Quantity");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 116, 134, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Price");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 121, -1));

        BookIdTb.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        BookIdTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BookIdTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIdTbActionPerformed(evt);
            }
        });
        jPanel2.add(BookIdTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 155, 60, -1));

        PriceTb.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PriceTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PriceTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTbActionPerformed(evt);
            }
        });
        jPanel2.add(PriceTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 155, 147, -1));

        TitleTb.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TitleTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TitleTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleTbActionPerformed(evt);
            }
        });
        jPanel2.add(TitleTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 155, 127, -1));

        AuthorTb.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        AuthorTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AuthorTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorTbActionPerformed(evt);
            }
        });
        jPanel2.add(AuthorTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 155, 119, -1));

        QuantityTb.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        QuantityTb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        QuantityTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTbActionPerformed(evt);
            }
        });
        jPanel2.add(QuantityTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 155, 159, -1));

        SaveBtn.setText("Save");
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 73, -1));

        EditTb.setText("Edit");
        EditTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditTbMouseClicked(evt);
            }
        });
        EditTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTbActionPerformed(evt);
            }
        });
        jPanel2.add(EditTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 73, -1));

        DeleteTb.setText("Delete");
        DeleteTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteTbMouseClicked(evt);
            }
        });
        DeleteTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTbActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 73, -1));

        ResetTb.setText("Reset");
        ResetTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetTbMouseClicked(evt);
            }
        });
        ResetTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetTbActionPerformed(evt);
            }
        });
        jPanel2.add(ResetTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 73, -1));

        BooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Author", "Category", "Quantity", "Price"
            }
        ));
        BooksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BooksTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 834, 170));

        PrintBtn.setText("Print");
        PrintBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintBtnMouseClicked(evt);
            }
        });
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });
        jPanel2.add(PrintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 73, -1));

        labelField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        labelField.setText("Author");
        labelField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(labelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 116, 99, -1));

        CategoryTb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiction", "Non-fiction", "Academics" }));
        jPanel2.add(CategoryTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 157, 129, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 1170, 580));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookshop/Close_new_new.PNG"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 100, 80));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Manage Books");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, 30));

        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\Book\\logout.PNG")); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookIdTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIdTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIdTbActionPerformed

    private void PriceTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTbActionPerformed

    private void TitleTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TitleTbActionPerformed

    private void AuthorTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorTbActionPerformed

    private void QuantityTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTbActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void EditTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTbActionPerformed

    private void DeleteTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteTbActionPerformed

    private void ResetTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetTbActionPerformed

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    Connection Con = null;
    Statement st = null;
    ResultSet Rs = null;
    
    private void DisplayBooks(){
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshop","root", "Akku1805");
            st = Con.createStatement();
            Rs = st.executeQuery("select * from bookshop.book");
            BooksTable.setModel(DbUtils.resultSetToTableModel(Rs));
        }
        catch(Exception e){
        }
    }
    
    private void Reset(){
        BookIdTb.setText("");
        TitleTb.setText("");
        AuthorTb.setText("");
        QuantityTb.setText("");
        CategoryTb.setSelectedIndex(0);
        PriceTb.setText("");
        
    }
    
    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked
        if(BookIdTb.getText().isEmpty() || TitleTb.getText().isEmpty() || AuthorTb.getText().isEmpty() || CategoryTb.getSelectedIndex() == -1 || QuantityTb.getText().isEmpty() || PriceTb.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"missing Information");
        }
        else{
            try{
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshop","root", "Akku1805");
                PreparedStatement add = Con.prepareStatement("insert into book values(?,?,?,?,?,?)");
                add.setInt(1,Integer.valueOf(BookIdTb.getText()));
                add.setString(2, TitleTb.getText());
                add.setString(3, AuthorTb.getText());
                add.setString(4, CategoryTb.getSelectedItem().toString());
                add.setInt(5, Integer.valueOf(QuantityTb.getText()));
                add.setInt(6, Integer.valueOf(PriceTb.getText()));
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this,"Book saved");
                DisplayBooks();
                Reset();
                //Con.close();
            }
            catch(Exception e){
                e.printStackTrace();
            }
        
        }
    }//GEN-LAST:event_SaveBtnMouseClicked

    private void ResetTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetTbMouseClicked
        Reset();
    }//GEN-LAST:event_ResetTbMouseClicked

    private void DeleteTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteTbMouseClicked
        
        if(BookIdTb.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"missing Information");
        }
        
        else{
            try{
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshop","root", "Akku1805");
                String BId = BookIdTb.getText();
                String Query = "Delete from bookshop.book where BId="+BId;
                Statement Delete = Con.createStatement();
                Delete.executeUpdate(Query);
                JOptionPane.showMessageDialog(this,"Book Deleted");
                DisplayBooks();
                Reset();
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_DeleteTbMouseClicked

    private void BooksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksTableMouseClicked
        DefaultTableModel model =(DefaultTableModel)BooksTable.getModel();
        int MyIndex = BooksTable.getSelectedRow();
        BookIdTb.setText(model.getValueAt(MyIndex, 0).toString());
        TitleTb.setText(model.getValueAt(MyIndex, 1).toString());
        AuthorTb.setText(model.getValueAt(MyIndex, 2).toString());
        CategoryTb.setSelectedItem(model.getValueAt(MyIndex, 3).toString());
        QuantityTb.setText(model.getValueAt(MyIndex, 4).toString());
        PriceTb.setText(model.getValueAt(MyIndex, 5).toString());
      
    }//GEN-LAST:event_BooksTableMouseClicked

    private void EditTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTbMouseClicked
       
        if(BookIdTb.getText().isEmpty() || TitleTb.getText().isEmpty() || AuthorTb.getText().isEmpty() || CategoryTb.getSelectedIndex() == -1 || QuantityTb.getText().isEmpty() || PriceTb.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"missing Information");
        }
        else{
            try{
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshop","root", "Akku1805");
                String BId = BookIdTb.getText();
                String Query = "Update bookshop.book set Title='"+TitleTb.getText()+"',Author = '"+AuthorTb.getText()+"', Category = '"+CategoryTb.getSelectedItem()+"', Quantity='"+QuantityTb.getText()+"', Price = '"+PriceTb.getText()+"' where BId = "+BId ;
                Statement Delete = Con.createStatement();
                Delete.executeUpdate(Query);
                JOptionPane.showMessageDialog(this,"Books Updated");
                DisplayBooks();
                Reset();
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_EditTbMouseClicked

    private void PrintBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintBtnMouseClicked
        try{
            BooksTable.print();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_PrintBtnMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMouseClicked
        new Users().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AuthorTb;
    private javax.swing.JTextField BookIdTb;
    private javax.swing.JTable BooksTable;
    private javax.swing.JComboBox<String> CategoryTb;
    private javax.swing.JButton DeleteTb;
    private javax.swing.JButton EditTb;
    private javax.swing.JTextField PriceTb;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JTextField QuantityTb;
    private javax.swing.JButton ResetTb;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField TitleTb;
    private javax.swing.JLabel User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelField;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables
}
